name: Deployment Using Ansible

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
        with:
          path: ansible/playbooks 

  deploy:
    needs: build
    runs-on: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Ansible playbook
        uses: ansible/ansible-runner-github-action@v1
        with:
          playbook: ansible/playbooks/webserver.yml
          inventory: ansible/inventory.ini